import ProductReview from "./ProductReview";

export default interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  quantity: number;
  sold: number;
  brand: string;
  description: string;
  images: string[];
  reviews: ProductReview[];
}

export const calculateAverageRating = (product: Product): number => {
  if (product.reviews.length === 0) return 0;

  const totalRatings = product.reviews.reduce(
    (sum, review) => sum + review.rating,
    0
  );
  return +(totalRatings / product.reviews.length).toFixed(1);
};

export const sampleProducts: Product[] = [
  {
    id: 1,
    name: "UV Expert Defense SPF 50+",
    price: 60,
    category: "Sunscreen",
    quantity: 2,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 2,
    name: "Dreamskin Fresh & Perfect Face Cushion SPF 50",
    price: 90,
    category: "Sunscreen",
    quantity: 8,
    sold: 0,
    brand: "Dior",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 3,
    name: "Mineral Unseen Sunscreen SPF 40",
    price: 40,
    category: "Sunscreen",
    quantity: 4,
    sold: 0,
    brand: "Supergoop!",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 4,
    name: "Advanced Génifique Radiance Boosting Face Serum",
    price: 160,
    category: "Serum",
    quantity: 4,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 5,
    name: "Capture Totale Le Sérum Anti-Aging Serum",
    price: 125,
    category: "Serum",
    quantity: 5,
    sold: 0,
    brand: "Dior",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 6,
    name: "GOOPGENES All-In-One Super Nutrient Face Serum",
    price: 105,
    category: "Serum",
    quantity: 3,
    sold: 0,
    brand: "Supergoop!",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 7,
    name: "The Dewy Serum Resurfacing and Plumping Treatment",
    price: 89,
    category: "Serum",
    quantity: 9,
    sold: 0,
    brand: "Tatcha",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 8,
    name: "Clarifique Double Treatment Hydrating & Exfoliating Essence",
    price: 95,
    category: "Serum",
    quantity: 4,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 9,
    name: "Advanced Génifique Night Cream with Triple Ceramide Complex",
    price: 100,
    category: "Skincare",
    quantity: 5,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 10,
    name: "Bi-Facil Double-Action Eye Makeup Remover",
    price: 45,
    category: "Makeup Remover",
    quantity: 6,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 11,
    name: "La Vie Est Belle Fragrance",
    price: 120,
    category: "Fragrance",
    quantity: 0,
    sold: 0,
    brand: "Lancôme",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 12,
    name: "La Mousse OFF/ON Foaming Face Cleanser",
    price: 52,
    category: "Cleanser",
    quantity: 5,
    sold: 0,
    brand: "Dior",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 13,
    name: "Capture Totale Hyalushot: Wrinkle Corrector with Hyaluronic Acid",
    price: 85,
    category: "Skincare",
    quantity: 3,
    sold: 0,
    brand: "Dior",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 14,
    name: "Miss Dior Parfum",
    price: 175,
    category: "Fragrance",
    quantity: 6,
    sold: 0,
    brand: "Dior",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 15,
    name: "Superscreen Rich Hydrating Cream SPF 40 Moisturizer Face Sunscreen",
    price: 62,
    category: "Sunscreen",
    quantity: 5,
    sold: 0,
    brand: "Supergoop!",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 16,
    name: "The Silk Sunscreen SPF 50 Weightless Mineral Sunscreen",
    price: 72,
    category: "Sunscreen",
    quantity: 5,
    sold: 0,
    brand: "Tatcha",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 17,
    name: "The Matcha Cleanse Daily Clarifying Gel Cleanser",
    price: 58,
    category: "Cleanser",
    quantity: 5,
    sold: 0,
    brand: "Tatcha",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 18,
    name: "The Indigo Cleansing Balm Moisturizing Makeup Remover",
    price: 48,
    category: "Makeup Remover",
    quantity: 5,
    sold: 0,
    brand: "Tatcha",
    description: "",
    images: [],
    reviews: [],
  },
  {
    id: 19,
    name: "Luminous Dewy Skin Mist",
    price: 72,
    category: "Skincare",
    quantity: 5,
    sold: 0,
    brand: "Tatcha",
    description: "",
    images: [],
    reviews: [],
  },
];
